### ISSUE TITLE
libfaad2.dll mingw

### ISSUE THREAD

**Issue by artenax** [knik0/faad2#154]
I can't compile libfaad2.dll even with --enable-shared --disable-static options. Only faad.exe and .a files are created.
libfaad2.dll can only be compiled in msvc?

**Comment by fabiangreffrath** [comment]
Do you try to build the release or latest master?

**Comment by artenax** [comment]
I tried 2.10.1 and 2.8 versions. The reason is the LDFLAGS="-static" option, but without it there is a dependency on other .dll libraries.
I am using cross compilation on Linux.
The master version uses cmake and an error appears when compiling (I used CMAKE_TOOLCHAIN_FILE).

**Comment by eustas** [comment]
Will try on master; and add to CI, if possible.

**Comment by eustas** [comment]
Currently MSYS2 builds are failing because of `_asm` directives (for fixed point builds). Looking for solution.

**Comment by fabiangreffrath** [comment]
Add `&& !defined(__GNUC__)` here?
https://github.com/knik0/faad2/blob/c085498de39151c108f67a6bf90af9e5eb553810/libfaad/fixed.h#L68

**Comment by artenax** [comment]
Thank you. Now the cross-compilation works.
```
git clone https://github.com/knik0/faad2
cd faad2
mkdir -p build-dir && cd build-dir
cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=/home/denis/faad2/build-dir/install \
-DCMAKE_TOOLCHAIN_FILE=/home/denis/mingw.cmake -DCMAKE_BUILD_TYPE=Release \
-DBUILD_SHARED_LIBS=ON
```
mingw.cmake:
```
# the name of the target operating system
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(TOOLCHAIN_PREFIX i686-w64-mingw32)

# which compilers to use for C and C++
set(CMAKE_C_COMPILER   i686-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)
set(CMAKE_RC_COMPILER  i686-w64-mingw32-windres)

# where is the target environment located
set(CMAKE_FIND_ROOT_PATH  /usr/i686-w64-mingw32)

# adjust the default behavior of the FIND_XXX() commands:
# search programs in the host environment
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# search headers and libraries in the target environment
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_FIND_LIBRARY_SUFFIXES ".a;.dll.a")
set(CMAKE_EXE_LINKER_FLAGS "-static")
```
