### ISSUE TITLE
Incorrect table boundaries checks in huffmanc.c

### ISSUE THREAD

**Issue by atimmernans** [knik0/faad2#192]
1) the tables sizes seem often incorrect (usually overestimated), I think they should be:

static const int hcb_2_quad_table_size[] = { 0, 113, 85, 0, 184, 0, 0, 0, 0, 0, 0, 0 };
static const int hcb_2_pair_table_size[] = { 0, 0, 0, 0, 0, 0, 125, 0, 83, 0, 209, 374 };
static const int hcb_bin_table_size[] = { 0, 0, 0, 161, 0, 161, 0, 127, 0, 337, 0, 0 };

Note: I think it would be best to add "static const " to all the tables in huffman.c and in the codebooks and check the sizes of the codebooks by explicitly specify the sizes of those arrays and as a test reducing those sizes by 1 to check that they generate a "too many initializers" error.

2) the checks of variable offset against the table size should be offset >= table size and not offset > table size.
3) the checks of variable offset against the table size should be placed before accessing the table, not after (see lines 186, 229, 261, 295).
4) offset is not checked at all in function huffman_spectral_data_2()

**Comment by fabiangreffrath** [comment]
Thank you very much for your reports here and in #191 ! However, I'd appreciate if you could provide pull requests with your suggested changes instead of formulating them as clear text. It is much easier to discuss actual code changes than write text about what should be changed which way. :wink: Thank you!

**Comment by eustas** [comment]
I'll take a look at this soon.

**Comment by eustas** [comment]
Checked hcb_2_quad_table_size. Actually, size/offset check is no-op due to correctness of 2-level Huffman reading algorithm. Preparing PR that clarifies that piece of code.

**Comment by eustas** [comment]
I believe we can close this issue now. I'll take a look on the #191 soon.

**Comment by fabiangreffrath** [comment]
Alright, fine with me. Thank you!
