### ISSUE TITLE
faad2-2.9.0 missing include

### ISSUE THREAD

**Issue by vividos** [knik0/faad2#41]
I'm trying to compile libfaad2 version 2.9.0 with Visual Studio, and there's one include file missing. In ps_dec.c there are some `fprintf(stderr, ` statements, and the compiler can't find stderr. The include that I had to add at the top was

    #include <stdio.h>

It would be nice if later versions of libfaad2 sources could include the line. Thanks!

**Comment by zvezdochiot** [comment]
@vividos say:
>In ps_dec.c

It is advisable to refer directly to the code. In this way:
https://github.com/knik0/faad2/blob/365532ebc7772464a1aa17cefd3bfdce6648266d/libfaad/ps_dec.c#L35-L37

**Comment by fabiangreffrath** [comment]
> It would be nice if later versions of libfaad2 sources could include the line

Done so, thanks for the report. Speaking of future releases, @hlef did you find some time to have a look at #17 and #35 ? :wink:

**Comment by vividos** [comment]
Thanks!
