### ISSUE TITLE
Was libmp4ff removed?

### ISSUE THREAD

**Issue by Jacalz** [knik0/faad2#45]
I am looking at updating the Solus package to the latest version of faad2 as this mirror carries a bunch of development and security fixes over the versions downloadable from the sourceforge page. When building version 2.9.1, I get removals of stuff related to `libmp4ff` and we have a couple references to code that doesn't exist in this codebase. For example, the whole folder called `common`, that was in the root of the project, is totally gone.

Download [here](https://downloads.sourceforge.net/project/faac/faad2-src/faad2-2.8.0/faad2-2.8.8.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Ffaac%2Ffiles%2Ffaad2-src%2Ffaad2-2.8.0%2Ffaad2-2.8.8.tar.gz%2Fdownload&ts=1576086035) and you'll see the common folder there in all it's glory. Any chance we could get that added back in, unless the functionality isn't used anymore?

If you add it back in, it might be worth to add in the improvements of [this patch](https://dev.getsol.us/source/faad/browse/master/files/faad2-2.8.3-libmp4ff-shared-lib.patch) to the codebase.

Here's a git diff over removals:
```
     <Package>
         <Name>faad</Name>
@@ -28,8 +28,6 @@ profile, MPEG-2 and MPEG-4 AAC decoder. FAAD2 includes code for SBR
             <Path fileType="library">/usr/lib64/libfaad.so.2.0.0</Path>
             <Path fileType="library">/usr/lib64/libfaad_drm.so.2</Path>
             <Path fileType="library">/usr/lib64/libfaad_drm.so.2.0.0</Path>
-            <Path fileType="library">/usr/lib64/libmp4ff.so.0</Path>
-            <Path fileType="library">/usr/lib64/libmp4ff.so.0.0.0</Path>
         </Files>
     </Package>
     <Package>
@@ -41,16 +39,13 @@ profile, MPEG-2 and MPEG-4 AAC decoder. FAAD2 includes code for SBR
 </Description>
         <PartOf>programming.devel</PartOf>
         <RuntimeDependencies>
-            <Dependency release="7">faad</Dependency>
+            <Dependency release="8">faad</Dependency>
         </RuntimeDependencies>
         <Files>
             <Path fileType="header">/usr/include/faad.h</Path>
-            <Path fileType="header">/usr/include/mp4ff.h</Path>
-            <Path fileType="header">/usr/include/mp4ffint.h</Path>
             <Path fileType="header">/usr/include/neaacdec.h</Path>
             <Path fileType="library">/usr/lib64/libfaad.so</Path>
             <Path fileType="library">/usr/lib64/libfaad_drm.so</Path>
-            <Path fileType="library">/usr/lib64/libmp4ff.so</Path>
         </Files>
     </Package>
     <Package>
```

Abi symbol removals:
```
-libmp4ff.so.0:mp4ff_meta_get_artist
-libmp4ff.so.0:mp4ff_meta_get_by_index
-libmp4ff.so.0:mp4ff_meta_get_comment
-libmp4ff.so.0:mp4ff_meta_get_compilation
-libmp4ff.so.0:mp4ff_meta_get_coverart
-libmp4ff.so.0:mp4ff_meta_get_date
-libmp4ff.so.0:mp4ff_meta_get_disc
-libmp4ff.so.0:mp4ff_meta_get_genre
-libmp4ff.so.0:mp4ff_meta_get_num_items
-libmp4ff.so.0:mp4ff_meta_get_tempo
-libmp4ff.so.0:mp4ff_meta_get_title
-libmp4ff.so.0:mp4ff_meta_get_tool
-libmp4ff.so.0:mp4ff_meta_get_totaldiscs
-libmp4ff.so.0:mp4ff_meta_get_totaltracks
-libmp4ff.so.0:mp4ff_meta_get_track
-libmp4ff.so.0:mp4ff_meta_get_writer
-libmp4ff.so.0:mp4ff_meta_index_to_genre
-libmp4ff.so.0:mp4ff_meta_update
-libmp4ff.so.0:mp4ff_num_samples
-libmp4ff.so.0:mp4ff_open_read
-libmp4ff.so.0:mp4ff_open_read_metaonly
-libmp4ff.so.0:mp4ff_parse_metadata
-libmp4ff.so.0:mp4ff_position
-libmp4ff.so.0:mp4ff_read_char
-libmp4ff.so.0:mp4ff_read_data
-libmp4ff.so.0:mp4ff_read_int16
-libmp4ff.so.0:mp4ff_read_int24
-libmp4ff.so.0:mp4ff_read_int32
-libmp4ff.so.0:mp4ff_read_int64
-libmp4ff.so.0:mp4ff_read_mp4_descr_length
-libmp4ff.so.0:mp4ff_read_sample
-libmp4ff.so.0:mp4ff_read_sample_getsize
-libmp4ff.so.0:mp4ff_read_sample_v2
-libmp4ff.so.0:mp4ff_read_string
-libmp4ff.so.0:mp4ff_set_position
-libmp4ff.so.0:mp4ff_set_sample_position
-libmp4ff.so.0:mp4ff_tag_delete
-libmp4ff.so.0:mp4ff_time_scale
-libmp4ff.so.0:mp4ff_total_tracks
-libmp4ff.so.0:mp4ff_truncate
-libmp4ff.so.0:mp4ff_write_data
-libmp4ff.so.0:mp4ff_write_int32
-libmp4ff.so.0:parse_atoms
-libmp4ff.so.0:parse_sub_atoms
```

**Comment by fabiangreffrath** [comment]
libmp4ff was removed on purpose by faad2's formerly active maintainer @knik0 and replaced by a rudimentary MP4 container implementation in https://github.com/knik0/faad2/blob/master/frontend/mp4read.c. 
However, if you plan to further maintain mp4ff, you will still find it up to the 2_8_8 tag.

**Comment by Jacalz** [comment]
Is the new implementation a full drop in replacement or are can there be consequences of broken packages with mp4ff removed?

**Comment by fabiangreffrath** [comment]
I fear not, I guess it is tailored down to the faad2 frontend's needs. And I am sure there are still some bugs left as @knik0 disappeared rather suddenly during the development process. If you need a full-blown MP4 file format implementation, I'd suggest to use ffmpeg's libavformat, libmp4v2 (MPL!) or gpac instead.

**Comment by Jacalz** [comment]
Thanks. I will see about getting this package updated in the Solus repository then. Arch Linux are already using the latest version here, so I'd expect the break to be minimal. Thanks for the information and thanks for keeping on developing this :)

**Comment by fabiangreffrath** [comment]
This change only affects the CLI frontend anyway, the library never had its own MP4 parser.

> thanks for keeping on developing this

More by accident, I was left as the only one with commit rights when the original maintainer disappeared.

**Comment by Jacalz** [comment]
Alright. Just a little fyi, the README file still contains references to common and libmp4ff...
