### ISSUE TITLE
ALAC (Apple Lossless Audio Codec) support in faad

### ISSUE THREAD

**Issue by poetnerd** [knik0/faad2#75]
The Logitech Media Server uses a fork of faad 2.7 that contains support for parsing Apple Lossless Audio Codec (ALAC) format.  Unfortunately that support was never submitted upstream.

Is there interest in adding ALAC support to faad?

Although the mp4 parser rewrite means that the original mods to add ALAC support cannot be integrated as-is, if adding ALAC support is a direction the faad2 maintainers think is a good one, I'd be willing to help get the changes rewritten to work with the current version.

**Comment by eustas** [comment]
Wikipedia says "ALAC is not a variant of [AAC](https://en.wikipedia.org/wiki/Advanced_Audio_Coding) (which is a [lossy](https://en.wikipedia.org/wiki/Lossy_compression) format), but rather an unrelated lossless format that uses [linear prediction](https://en.wikipedia.org/wiki/Linear_prediction) (similar to other lossless codecs)."

Indeed, links from apple point to https://github.com/macosforge/alac.git

Brief search in https://github.com/Logitech/slimserver shows that they use both `faad` and `alac` binaries.

As discussed in other issue, perhaps it is better to look into other project that would cover mp4 format in all the details and relay actual decoding to libfaad, libalac, etc.

I propose to close this issue as a non-goal.

**Comment by fabiangreffrath** [comment]
Alright, thank you.
