### ISSUE TITLE
aac stream will not play

### ISSUE THREAD

**Issue by dln949** [knik0/faad2#76]
libfaad2 2.9.1-1 installed on ubuntu 20.04

Started having problems with some streams - for some reason, I now get no audio.  For example, for this stream:  [http://stream.open.fm/68](url) generates this error message in the mpd log:  

"faad_decoder: error decoding AAC stream: Unexpected channel configuration change"  

What does this error message mean?  

What should I do to fix this problem?  

Thanks.

**Comment by eustas** [comment]
I can see 3 codepaths that report this error, and one extra that has been fixed in 2.9.2 (https://github.com/knik0/faad2/pull/51)

@dln949 could you kindly check if this problem has been fixed, or still exists? (e.g. on Ubuntu 22.04 LTS)? Thanks.

**Comment by dln949** [comment]
@eustas , sorry, but I no longer have access to the system to try this on.

**Comment by eustas** [comment]
No worries. I could try it myself; just say what software you have used to play the stream. Thanks.

**Comment by dln949** [comment]
I am so sorry!!  But, it has been over one year since I was trying this, my inadequate brain can't recall that.  Sorry to let you down.

**Comment by eustas** [comment]
Found `qmmp` player that uses `libfaad`. It seems to work with the mentioned URL. So we can close this issue for now, and reopen if the problem happens again =)

**Comment by fabiangreffrath** [comment]
> Found `qmmp` player that uses `libfaad`. It seems to work with the mentioned URL. So we can close this issue for now, and reopen if the problem happens again =)

Thank you!

Please give me a hint when you consider your fixes finished, so I can tag a new release. 😉

**Comment by eustas** [comment]
Surely. I'm going to add few more fuzzers. Soon oss-fuzz will start crunching... It is a good practice to give it a week or so (given no new bugs appear). I'll send you a message when it is time =)
